[package]
name = "receipt_repository_api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
bigdecimal = { version = "0.4.4", features = ["serde"] }
chrono = { version = "0.4.38", features = ["default", "serde"] }
diesel = { version = "2.2.1", features = ["postgres", "extras"] }
dotenvy = "0.15.7"
serde = { version = "1.0.203", features = ["std", "serde_derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
